// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: feed_follows.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH inserted as (
    INSERT INTO feed_follows (user_id, feed_id, created_at, updated_at)
    VALUES (
        $1,
        $2,
        $3,
        $4
    )
    RETURNING id, user_id, feed_id, created_at, updated_at
) SELECT i.id, i.user_id, i.feed_id, i.created_at, i.updated_at, u.name as user_name, f.name as feed_name FROM inserted i
INNER JOIN users u on u.id = i.user_id
INNER JOIN feeds f on f.id = i.feed_id
`

type CreateFeedFollowParams struct {
	UserID    uuid.UUID
	FeedID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreateFeedFollowRow struct {
	ID        int32
	UserID    uuid.UUID
	FeedID    int32
	CreatedAt time.Time
	UpdatedAt time.Time
	UserName  string
	FeedName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.UserID,
		arg.FeedID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FeedID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}

const deleteFeedFollowByUserAndFeed = `-- name: DeleteFeedFollowByUserAndFeed :exec
DELETE FROM feed_follows 
WHERE feed_follows.id IN (
    SELECT ff.id FROM feed_follows ff
    INNER JOIN users u on u.id = ff.user_id
    INNER JOIN feeds f on f.id = ff.feed_id
    WHERE u.id = $1 and f.url = $2
    )
`

type DeleteFeedFollowByUserAndFeedParams struct {
	ID  uuid.UUID
	Url string
}

func (q *Queries) DeleteFeedFollowByUserAndFeed(ctx context.Context, arg DeleteFeedFollowByUserAndFeedParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowByUserAndFeed, arg.ID, arg.Url)
	return err
}

const getFeedFollowsForUser = `-- name: GetFeedFollowsForUser :many
SELECT f.id, f.name, url, f.user_id, f.created_at, f.updated_at, last_fetched_at, ff.id, ff.user_id, feed_id, ff.created_at, ff.updated_at, u.id, u.name, u.created_at, u.updated_at, u.name as user_name FROM feeds f
INNER JOIN feed_follows ff on f.id = ff.feed_id
INNER JOIN users u on u.id = ff.user_id
WHERE ff.user_id = $1
`

type GetFeedFollowsForUserRow struct {
	ID            int32
	Name          string
	Url           string
	UserID        uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastFetchedAt sql.NullTime
	ID_2          int32
	UserID_2      uuid.UUID
	FeedID        int32
	CreatedAt_2   time.Time
	UpdatedAt_2   time.Time
	ID_3          uuid.UUID
	Name_2        string
	CreatedAt_3   time.Time
	UpdatedAt_3   time.Time
	UserName      string
}

func (q *Queries) GetFeedFollowsForUser(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserRow
	for rows.Next() {
		var i GetFeedFollowsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastFetchedAt,
			&i.ID_2,
			&i.UserID_2,
			&i.FeedID,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.ID_3,
			&i.Name_2,
			&i.CreatedAt_3,
			&i.UpdatedAt_3,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
